// Sample json data to output on UI.


const data = {
  body: [
    {
      name: "Auto Chess 1",
      region: "US",
      createdOn: 1652977467208,
      price: 23,
      csv: "Some CSV link for Auto Chess",
      report: "Some report link for Auto Chess",
      image_url: "1.png",
    },
    {
      name: "Auto Chess 2",
      region: "US",
      createdOn: 1653430776691,
      price: 23,
      csv: "Some CSV link for Auto Chess",
      report: "Some report link for Auto Chess",
      image_url: "1.png",
    },
    {
      name: "PUBG MOBILE",
      region: "CH",
      createdOn: 1592912516943,
      price: 120,
      csv: "Some CSV link for PUBG MOBILE",
      report: "Some report link for PUBG MOBILE",
      image_url: "5.png",
    },
    {
      name: "PUBG MOBILE 2",
      region: "CH",
      createdOn: 1591830637208,
      price: 120,
      csv: "Some CSV link for PUBG MOBILE",
      report: "Some report link for PUBG MOBILE",
      image_url: "5.png",
    },
    {
      name: "Flow Free",
      region: "FR",
      createdOn: 1652286267208,
      price: 40,
      csv: "Some CSV link for Flow Free",
      report: "Some report link for Flow Free",
      image_url: "2.png",
    },
    {
      name: "Flow Free 2",
      region: "FR",
      createdOn: 1592826116943,
      price: 40,
      csv: "Some CSV link for Flow Free",
      report: "Some report link for Flow Free",
      image_url: "2.png",
    },
    {
      name: "Garena Free Fire",
      region: "CH",
      createdOn: 1592940617208,
      price: 110,
      csv: "Some CSV link for Garena Free Fire",
      report: "Some report link for Garena Free Fire",
      image_url: "3.png",
    },
    {
      name: "MORTAL KOMBAT 2",
      region: "US",
      createdOn: 1592028584617,
      price: 200,
      csv: "Some CSV link for MORTAL KOMBAT",
      report: "Some report link for MORTAL KOMBAT",
      image_url: "4.png",
    },
    {
      name: "MORTAL KOMBAT 3",
      region: "US",
      createdOn: 1662631867208,
      price: 200,
      csv: "Some CSV link for MORTAL KOMBAT",
      report: "Some report link for MORTAL KOMBAT",
      image_url: "4.png",
    },
    {
      name: "Summoners War",
      region: "US",
      createdOn: 1592459067208,
      price: 90,
      csv: "Some CSV link for Summoners War",
      report: "Some report link for Summoners War",
      image_url: "8.png",
    },
    {
      name: "Summoners War 3",
      region: "US",
      createdOn: 1627319629746,
      price: 90,
      csv: "Some CSV link for Summoners War",
      report: "Some report link for Summoners War",
      image_url: "8.png",
    },
    {
      name: "Need for Speed No Limits",
      region: "US",
      createdOn: 2092070267208,
      price: 500,
      csv: "Some CSV link for Need for Speed No Limits",
      report: "Some report link for Need for Speed No Limits",
      image_url: "6.png",
    },
    {
      name: "Shadow Fight 2",
      region: "JP",
      createdOn: 2092739576691,
      price: 60,
      csv: "Some CSV link for Shadow Fight 3",
      report: "Some report link for Shadow Fight 3",
      image_url: "7.png",
    },
    {
      name: "Need for Speed No Limits",
      region: "FR",
      createdOn: 2092027067206,
      price: 60,
      csv: "Some CSV link for Shadow Fight 3",
      report: "Some report link for Shadow Fight 3",
      image_url: "6.png",
    },
    {
      name: "Need for Speed No Limits",
      region: "FR",
      createdOn: 2022027067206,
      price: 60,
      csv: "Some CSV link for Shadow Fight 3",
      report: "Some report link for Shadow Fight 3",
      image_url: "6.png",
    },
    {
      name: "Need for Speed No Limits",
      region: "FR",
      createdOn: 2092027067206,
      price: 60,
      csv: "Some CSV link for Shadow Fight 3",
      report: "Some report link for Shadow Fight 3",
      image_url: "6.png",
    },



  ],
};

export default data;
